---
title: "FAO dataset - Basic Exploration"
author: "Ingri Katherine Quevedo Rocha"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
options(scientific=T, digits = 3) 
```

```{r init, include=F}
library(ezids)
library(ggplot2)
library(tidyr)
library(dplyr)
setwd("C:/Users/k_the/main/01_intro_data_science/DataScienceProject")
```

# Opening and formatting the dataset
**Read the data file FAOSTAT Food Balance Sheet 2022**   
```{r}
faobs = read.csv("raw_data/FAOSTAT_data_filteredvars2022.csv", header=T)
str(faobs)
```

Remove variables we do not need
```{r}
faobs_s <- subset(faobs, select = c(Area, Element, Item, Value))
str(faobs_s)
```

```{r setup, include=FALSE}
rm(faobs)
```

Reshape to have each element in a different column
```{r setup}
faobs_s_wide = faobs_s%>%pivot_wider(names_from = Element, values_from = Value)
```

```{r setup, include=FALSE}
rm(faobs_s)
```

Fix Population Variable

```{r setup}
faobs_s_wide = faobs_s_wide%>%group_by(Area) %>%fill(`Total Population - Both sexes`, .direction = "downup") %>%ungroup()

faobs_clean <- faobs_s_wide %>%filter(Item != "Population")
```
```{r setup, include=FALSE}
rm(faobs_s_wide)
```

Export cleaned dataset

```{r setup}
write.csv(faobs_clean, "proc_data/faobs_clean.csv", row.names = FALSE)
```

